const DIFFICULTY = 2; // 7
const MINE_RATE = 30;
const MINING_REWARD = 25;
const INITIAL_BALANCE = 50;
const HALF_BLOCK_RATE = 300000; // 300000
const INITIAL_BALANCE_ADMIN = 50;

module.exports = {
	MINE_RATE,
	DIFFICULTY,
	MINING_REWARD,
	HALF_BLOCK_RATE,
	INITIAL_BALANCE,
	INITIAL_BALANCE_ADMIN
};